# Generated by Django 3.2 on 2022-09-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="is_blocked",
            field=models.BooleanField(
                default=False, help_text="Designates that this user has blocked.",
            ),
        ),
    ]
